# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: runtime/v1/task.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'runtime/v1/task.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15runtime/v1/task.proto\x12\nruntime.v1\"\xfb\x01\n\x04Task\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x12\n\nrequest_id\x18\x02 \x01(\t\x12\x10\n\x08trace_id\x18\x03 \x01(\t\x12\r\n\x05skill\x18\x04 \x01(\t\x12\x0f\n\x07payload\x18\x05 \x01(\x0c\x12\x10\n\x08priority\x18\x06 \x01(\x05\x12\x12\n\ntimeout_ms\x18\x07 \x01(\x01\x12\x30\n\x08metadata\x18\x08 \x03(\x0b\x32\x1e.runtime.v1.Task.MetadataEntry\x12\x13\n\x0bmax_retries\x18\t \x01(\x05\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x8d\x01\n\nTaskResult\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12&\n\x06status\x18\x02 \x01(\x0e\x32\x16.runtime.v1.TaskStatus\x12\x0e\n\x06result\x18\x03 \x01(\x0c\x12\r\n\x05\x65rror\x18\x04 \x01(\t\x12\x12\n\nlatency_ms\x18\x05 \x01(\x01\x12\x13\n\x0bretry_count\x18\x06 \x01(\x05\"$\n\x11\x43\x61ncelTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\"4\n\x12\x43\x61ncelTaskResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t*\xda\x01\n\nTaskStatus\x12\x1b\n\x17TASK_STATUS_UNSPECIFIED\x10\x00\x12\x17\n\x13TASK_STATUS_CREATED\x10\x01\x12\x16\n\x12TASK_STATUS_QUEUED\x10\x02\x12\x17\n\x13TASK_STATUS_RUNNING\x10\x03\x12\x19\n\x15TASK_STATUS_COMPLETED\x10\x04\x12\x16\n\x12TASK_STATUS_FAILED\x10\x05\x12\x17\n\x13TASK_STATUS_TIMEOUT\x10\x06\x12\x19\n\x15TASK_STATUS_CANCELLED\x10\x07\x32\xd7\x01\n\x10SchedulerService\x12\x36\n\nSubmitTask\x12\x10.runtime.v1.Task\x1a\x16.runtime.v1.TaskResult\x12>\n\x10SubmitTaskStream\x12\x10.runtime.v1.Task\x1a\x16.runtime.v1.TaskResult0\x01\x12K\n\nCancelTask\x12\x1d.runtime.v1.CancelTaskRequest\x1a\x1e.runtime.v1.CancelTaskResponseBBZ@github.com/ai-invest-agent/go-runtime/proto/runtime/v1;runtimev1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'runtime.v1.task_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z@github.com/ai-invest-agent/go-runtime/proto/runtime/v1;runtimev1'
  _globals['_TASK_METADATAENTRY']._loaded_options = None
  _globals['_TASK_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_TASKSTATUS']._serialized_start=528
  _globals['_TASKSTATUS']._serialized_end=746
  _globals['_TASK']._serialized_start=38
  _globals['_TASK']._serialized_end=289
  _globals['_TASK_METADATAENTRY']._serialized_start=242
  _globals['_TASK_METADATAENTRY']._serialized_end=289
  _globals['_TASKRESULT']._serialized_start=292
  _globals['_TASKRESULT']._serialized_end=433
  _globals['_CANCELTASKREQUEST']._serialized_start=435
  _globals['_CANCELTASKREQUEST']._serialized_end=471
  _globals['_CANCELTASKRESPONSE']._serialized_start=473
  _globals['_CANCELTASKRESPONSE']._serialized_end=525
  _globals['_SCHEDULERSERVICE']._serialized_start=749
  _globals['_SCHEDULERSERVICE']._serialized_end=964
# @@protoc_insertion_point(module_scope)
