// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: runtime/v1/task.proto

package runtimev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskStatus int32

const (
	TaskStatus_TASK_STATUS_UNSPECIFIED TaskStatus = 0
	TaskStatus_TASK_STATUS_CREATED     TaskStatus = 1
	TaskStatus_TASK_STATUS_QUEUED      TaskStatus = 2
	TaskStatus_TASK_STATUS_RUNNING     TaskStatus = 3
	TaskStatus_TASK_STATUS_COMPLETED   TaskStatus = 4
	TaskStatus_TASK_STATUS_FAILED      TaskStatus = 5
	TaskStatus_TASK_STATUS_TIMEOUT     TaskStatus = 6
	TaskStatus_TASK_STATUS_CANCELLED   TaskStatus = 7
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "TASK_STATUS_UNSPECIFIED",
		1: "TASK_STATUS_CREATED",
		2: "TASK_STATUS_QUEUED",
		3: "TASK_STATUS_RUNNING",
		4: "TASK_STATUS_COMPLETED",
		5: "TASK_STATUS_FAILED",
		6: "TASK_STATUS_TIMEOUT",
		7: "TASK_STATUS_CANCELLED",
	}
	TaskStatus_value = map[string]int32{
		"TASK_STATUS_UNSPECIFIED": 0,
		"TASK_STATUS_CREATED":     1,
		"TASK_STATUS_QUEUED":      2,
		"TASK_STATUS_RUNNING":     3,
		"TASK_STATUS_COMPLETED":   4,
		"TASK_STATUS_FAILED":      5,
		"TASK_STATUS_TIMEOUT":     6,
		"TASK_STATUS_CANCELLED":   7,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_runtime_v1_task_proto_enumTypes[0].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_runtime_v1_task_proto_enumTypes[0]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_runtime_v1_task_proto_rawDescGZIP(), []int{0}
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	TraceId       string                 `protobuf:"bytes,3,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Skill         string                 `protobuf:"bytes,4,opt,name=skill,proto3" json:"skill,omitempty"`
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"` // JSON-serialized dict
	Priority      int32                  `protobuf:"varint,6,opt,name=priority,proto3" json:"priority,omitempty"`
	TimeoutMs     float64                `protobuf:"fixed64,7,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MaxRetries    int32                  `protobuf:"varint,9,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"` // 0 = no retry
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_runtime_v1_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_runtime_v1_task_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Task) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Task) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *Task) GetSkill() string {
	if x != nil {
		return x.Skill
	}
	return ""
}

func (x *Task) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Task) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Task) GetTimeoutMs() float64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *Task) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Task) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

type TaskResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        TaskStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=runtime.v1.TaskStatus" json:"status,omitempty"`
	Result        []byte                 `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"` // JSON-serialized result data
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	LatencyMs     float64                `protobuf:"fixed64,5,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	RetryCount    int32                  `protobuf:"varint,6,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_runtime_v1_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_runtime_v1_task_proto_rawDescGZIP(), []int{1}
}

func (x *TaskResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResult) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *TaskResult) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *TaskResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *TaskResult) GetLatencyMs() float64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *TaskResult) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

type CancelTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskRequest) Reset() {
	*x = CancelTaskRequest{}
	mi := &file_runtime_v1_task_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskRequest) ProtoMessage() {}

func (x *CancelTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_task_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskRequest.ProtoReflect.Descriptor instead.
func (*CancelTaskRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_task_proto_rawDescGZIP(), []int{2}
}

func (x *CancelTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type CancelTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskResponse) Reset() {
	*x = CancelTaskResponse{}
	mi := &file_runtime_v1_task_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskResponse) ProtoMessage() {}

func (x *CancelTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_task_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskResponse.ProtoReflect.Descriptor instead.
func (*CancelTaskResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_task_proto_rawDescGZIP(), []int{3}
}

func (x *CancelTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelTaskResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_runtime_v1_task_proto protoreflect.FileDescriptor

const file_runtime_v1_task_proto_rawDesc = "" +
	"\n" +
	"\x15runtime/v1/task.proto\x12\n" +
	"runtime.v1\"\xde\x02\n" +
	"\x04Task\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x19\n" +
	"\btrace_id\x18\x03 \x01(\tR\atraceId\x12\x14\n" +
	"\x05skill\x18\x04 \x01(\tR\x05skill\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12\x1a\n" +
	"\bpriority\x18\x06 \x01(\x05R\bpriority\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\a \x01(\x01R\ttimeoutMs\x12:\n" +
	"\bmetadata\x18\b \x03(\v2\x1e.runtime.v1.Task.MetadataEntryR\bmetadata\x12\x1f\n" +
	"\vmax_retries\x18\t \x01(\x05R\n" +
	"maxRetries\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc3\x01\n" +
	"\n" +
	"TaskResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12.\n" +
	"\x06status\x18\x02 \x01(\x0e2\x16.runtime.v1.TaskStatusR\x06status\x12\x16\n" +
	"\x06result\x18\x03 \x01(\fR\x06result\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x05 \x01(\x01R\tlatencyMs\x12\x1f\n" +
	"\vretry_count\x18\x06 \x01(\x05R\n" +
	"retryCount\",\n" +
	"\x11CancelTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"D\n" +
	"\x12CancelTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error*\xda\x01\n" +
	"\n" +
	"TaskStatus\x12\x1b\n" +
	"\x17TASK_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13TASK_STATUS_CREATED\x10\x01\x12\x16\n" +
	"\x12TASK_STATUS_QUEUED\x10\x02\x12\x17\n" +
	"\x13TASK_STATUS_RUNNING\x10\x03\x12\x19\n" +
	"\x15TASK_STATUS_COMPLETED\x10\x04\x12\x16\n" +
	"\x12TASK_STATUS_FAILED\x10\x05\x12\x17\n" +
	"\x13TASK_STATUS_TIMEOUT\x10\x06\x12\x19\n" +
	"\x15TASK_STATUS_CANCELLED\x10\a2\xd7\x01\n" +
	"\x10SchedulerService\x126\n" +
	"\n" +
	"SubmitTask\x12\x10.runtime.v1.Task\x1a\x16.runtime.v1.TaskResult\x12>\n" +
	"\x10SubmitTaskStream\x12\x10.runtime.v1.Task\x1a\x16.runtime.v1.TaskResult0\x01\x12K\n" +
	"\n" +
	"CancelTask\x12\x1d.runtime.v1.CancelTaskRequest\x1a\x1e.runtime.v1.CancelTaskResponseBBZ@github.com/ai-invest-agent/go-runtime/proto/runtime/v1;runtimev1b\x06proto3"

var (
	file_runtime_v1_task_proto_rawDescOnce sync.Once
	file_runtime_v1_task_proto_rawDescData []byte
)

func file_runtime_v1_task_proto_rawDescGZIP() []byte {
	file_runtime_v1_task_proto_rawDescOnce.Do(func() {
		file_runtime_v1_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_runtime_v1_task_proto_rawDesc), len(file_runtime_v1_task_proto_rawDesc)))
	})
	return file_runtime_v1_task_proto_rawDescData
}

var file_runtime_v1_task_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_runtime_v1_task_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_runtime_v1_task_proto_goTypes = []any{
	(TaskStatus)(0),            // 0: runtime.v1.TaskStatus
	(*Task)(nil),               // 1: runtime.v1.Task
	(*TaskResult)(nil),         // 2: runtime.v1.TaskResult
	(*CancelTaskRequest)(nil),  // 3: runtime.v1.CancelTaskRequest
	(*CancelTaskResponse)(nil), // 4: runtime.v1.CancelTaskResponse
	nil,                        // 5: runtime.v1.Task.MetadataEntry
}
var file_runtime_v1_task_proto_depIdxs = []int32{
	5, // 0: runtime.v1.Task.metadata:type_name -> runtime.v1.Task.MetadataEntry
	0, // 1: runtime.v1.TaskResult.status:type_name -> runtime.v1.TaskStatus
	1, // 2: runtime.v1.SchedulerService.SubmitTask:input_type -> runtime.v1.Task
	1, // 3: runtime.v1.SchedulerService.SubmitTaskStream:input_type -> runtime.v1.Task
	3, // 4: runtime.v1.SchedulerService.CancelTask:input_type -> runtime.v1.CancelTaskRequest
	2, // 5: runtime.v1.SchedulerService.SubmitTask:output_type -> runtime.v1.TaskResult
	2, // 6: runtime.v1.SchedulerService.SubmitTaskStream:output_type -> runtime.v1.TaskResult
	4, // 7: runtime.v1.SchedulerService.CancelTask:output_type -> runtime.v1.CancelTaskResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_runtime_v1_task_proto_init() }
func file_runtime_v1_task_proto_init() {
	if File_runtime_v1_task_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_runtime_v1_task_proto_rawDesc), len(file_runtime_v1_task_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_runtime_v1_task_proto_goTypes,
		DependencyIndexes: file_runtime_v1_task_proto_depIdxs,
		EnumInfos:         file_runtime_v1_task_proto_enumTypes,
		MessageInfos:      file_runtime_v1_task_proto_msgTypes,
	}.Build()
	File_runtime_v1_task_proto = out.File
	file_runtime_v1_task_proto_goTypes = nil
	file_runtime_v1_task_proto_depIdxs = nil
}
